lib/zkevm_node.star
=> fix: l2 gas pricer is not running

main.star
=> fix: `args` aliasing issue

ethereum.star
https://github.com/kurtosis-tech/ethereum-package/releases/tag/2.1.0
=> chore: bump `ethereum-package` from `2.0.0` to `2.1.0`

README.org, docs/fork-id-migration.org, params.yml, templates/deploy_parameters.json
Adding some minor context for how to run the permissionless package standalone. Also adding some other minor fixes.
=> Mainnet / Testnet Permissionless Notes

README.org, scripts/tool_check.sh
Follow up of #48 
This script checks if the user has the required tools installed and also the correct versions.
For macOS users, it also checks if container private IP addresses are exposed and reachable.
```bash
$ ./scripts/tool_check.sh
Ensuring all required tools and versions are installed for deploying the Kurtosis CDK package...
✅ kurtosis 0.88.14 is installed, meets the requirement (>=0.88.9)
✅ docker 25.0.3 is installed, meets the requirement (>=24.7)
✅ jq 1.7.1 is installed
✅ yq 4.43.1 is installed, meets the requirement (>=4)
✅ cast 0.2.0 is installed
✅ polycli v0.1.42-10-g6ff76dd is installed
Checking macOS specific tools...
✅ docker-mac-connect 0.1.2 is installed
Running a dummy nginx container...
nginx
f365759ec710447ad910260b459ac1135aeba28a1e9c27fffd5ac46b71503bf6
Making an …
```
=> chore: script to check if necessary tools are installed

docs/trigger-a-reorg/network-helper.Dockerfile, docs/trigger-a-reorg/reorg.patch, docs/trigger-a-reorg/trigger-a-reorg.md
Simulate a reorg on L1 in order to test for bugs and document various recovery procedures.
https://polygon.atlassian.net/browse/DVT-1428
=> docs: simulate blockchain reorg on l1

cdk_bridge_infra.star, lib/zkevm_bridge.star
=> update bridge config to use the `l1_rpc_url` defined in `params.yml`

lib/zkevm_bridge.star
=> chore: lint

README.md
- Add back the architecture diagram and kurtosis-cdk testing commands.
- Fix LICENSE-APACHEl file link
=> docs: update `README`

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/docs_issue.yml, .github/ISSUE_TEMPLATE/feature_request.yml, .github/issue-labeler.yml, .github/pull_request_template.md
Most of it came from https://github.com/kurtosis-tech/kurtosis/tree/main/.github/ISSUE_TEMPLATE
=> feat: add issue and pr templates

docs/index.md
Fix a small typo on the overview page and reword the first sentence a little.
=> Small typo on overview page

params.yml, templates/contract-deploy/run-contract-setup.sh
Make the l1 funding amount configurable. The aim is to be able to use the Kurtosis CDK against Sepolia easily.
https://polygon.atlassian.net/browse/DVT-1466
=> feat: make l1 funding amount configurable

docs/how-to/use-native-token.md, mkdocs.yml
This PR has some small language clarifications.
=> docs: language clarifications

cdk_blutgang.star, main.star
- Add default l1 additional services (duplicate of #79)
- Lint code.
=> chore: minor fixes

.github/workflows/deploy.yml, .github/workflows/docker-image-builder-cron.yml, .github/workflows/lint.yml, .github/workflows/regression-tests.yml, ethereum.star
Prevent new releases to break our package.
https://polygon.atlassian.net/browse/DVT-1482
=> fix: use specific versions of kurtosis, geth and lighthouse

.github/ISSUE_TEMPLATE/bug_report.yml
Some of our users encountered problems when deploying our stack, related to the version of Kurtosis they were using.
https://github.com/0xPolygon/kurtosis-cdk/issues/96#issuecomment-2084482687
=> chore: ask for kurtosis-cli and engine versions in bug report issue template

.github/workflows/deploy.yml, docs/how-to/migrate/forkid-7-to-9.md, docs/quickstart/breakdown-deployment.md, docs/quickstart/set-up-node.md, main.star, params.yml
Some of the docs were out of date, this PR fixes that.
🚨 This PR also disables deployment of the permissionless node and the Ethereum load balance by default.
https://docs.polygon.technology/cdk/get-started/quickstart/set-up-node/#sync-an-external-permissionless-node
=> docs: update out of date docs

input_parser.star, main.star, scripts/compare_default_params.sh
Move input args to another file for clarity, so main.star remains well readable
Also modules are loaded on demand, as Tedi textually said: "this makes a lotta sense! you'll get only the modules you need to run your infra" and he liked it :100:
=> Move default args to input_parser file

doc-drafts/deploy-sepolia-l1.md
Add debugging information for contract deployment failures with Sepolia L1 deployment on Kurtosis-CDK.
=> docs: add debugging info in Sepolia deployment doc

.github/workflows/deploy.yml, .github/workflows/docker-image-builder-cron.yml, docker/README.md, docker/toolbox.Dockerfile, input_parser.star, kurtosis.yml, lib/service.star, main.star, params.yml, templates/bridge-infra/bridge-config.toml, templates/get-rollup-info.sh, workload.star
You can now specify the rollup manager address in addition to the zkevm rollup chain id in `params.yml` to automatically retrieve the rollup data from the `RollupManager` contract.
```yaml
zkevm_rollup_chain_id: 10101
zkevm_rollup_fork_id: 9
zkevm_rollup_manager_address: "0x2F50ef6b8e8Ee4E579B17619A92dE3E2ffbD8AD2"
```
This feature allows to use pre-deployed contracts on L1 which could speed up local deployments - you only need to deploy L1 and contracts once and then you can specify the address of the rollup manager contract - and it could also enable starting the stack against any L1 like Sepolia.
A new job has been introduced to test the behaviour of the package against a local L1 chain with pre-deployed zkevm contracts (see `pre-deployed-contracts`).
This PR also fixes a problem with …
=> feat: enable support for pre-deployed contracts

.github/workflows/regression-tests.yml
[git action] refactor to use cdk-kurtosis shared action
superusers can now create custom cdk devnet easier than ever before
=> [git action] refactor to use cdk-kurtosis shared action

deploy_zkevm_contracts.star
Iterate over array instead of repeating same code for multiple artifacts
=> Iterate artifacts over config

docs/how-to/migrate/forkid-7-to-9.md, docs/how-to/use-native-token.md, docs/quickstart/set-up-permissionless-node.md
=> docs: fix typos

.github/workflows/deploy.yml, ethereum.star, main.star
- Add CI job to test cdk-erigon as a sequencer.
- Comment and document some of the speed up options in the ethereum-package.
- Deploy the cdk-erigon sequencer along the cdk central/trusted environment.
=> chore: cdk-erigon sequencer nits

.github/workflows/deploy.yml, README.md
This PR fixes the CI for cdk-erigon-sequencer
=> fix: use correct param file for cdk-erigon sequencer

observability.star
- Adds postgres database as grafana data source
https://github.com/0xPolygon/kurtosis-cdk/assets/18576915/f95bf2c0-f1fc-4429-ba31-8cc59b2673df
=> feat: add postgres datasource

scripts/tool_check.sh
Bump `kurtosis` version in script.
=> fix: bump kurtosis version in tool check script

README.md
specifies how to set the `ETH_RPC_URL` wen using erigon
=> Eth rpc url for erigon

observability.star
- Adds metrics from cdk-erigon to the prometheus instance
- Tested with 👀
=> feat: add cdk-erigon prometheus metrics

.github/workflows/deploy.yml, .github/workflows/nightly.yml
Test that the new cdk-erigon setup works fine with zkevm pless nodes (or rpc).
Also speed up the time it takes to deploy the stack by using a `1`s L1 block interval.
=> ci: deploy zkevm pless node in cdk environment

params.yml, templates/trusted-node/prover-config.json
- Document `sequencer_type` in `params.yml`.
- Remove additional whitespaces in prover config template.
=> chore: minor config update

agglayer-attach-cdk-params.yml, input_parser.star, kurtosis.yml, params.yml, templates/cdk-erigon/config.yml
Allow Erigon to accept and process pre-eip155 txs
=> Option for zkevm.allow-pre-eip155-transactions

README.md, docs/edit-contracts.md
New doc `docs/edit-contracts.md` instructs how to edit the L1 smart contracts. The example in this doc is merely a hello-world to demo the ability to change the contract and observe the change on a deployed kurtosis-cdk devnet. It is intended to be a resource for new devs approaching this repo for the first time.
=> doc: how to edit smart contracts on the L1

agglayer-attach-cdk-params.yml, input_parser.star, kurtosis.yml, params.yml
This version is compatible with arm64
=> chore: bump cdk version

src/additional_services/erpc.star
This PR updates the erpc image to the official release docker image
=> Use official erpc image

docs/deploy-using-sepolia.org, templates/trusted-node/cdk-node-config.toml
This PR addresses configs in the `cdk-node-config.toml` file. Tested deployment to Sepolia.
=> chore: minor updates to cdk-node-config

agglayer-attach-cdk-params.yml, input_parser.star, params.yml
This PR updates the `zkevm_pool_manager_image` version.
=> chore: update image for pool manager

templates/cdk-erigon/config.yml
- Add a small note when a cdk-erigon flag is not used in the code.
- Issues created in the cdk-erigon repo.
https://polygon.enterprise.slack.com/lists/T8VPLGV4Z/F07AWFULS49?record_id=Rec07N08QKC81
=> docs: document unused cdk-erigon flags in the code

input_parser.star, params.yml
This PR updates the `zkevm_pool_manager_image` to  `v0.1.1-RC2` version.
=> chore: update pool manager image

.github/tests/additional-services.yml, .github/workflows/deploy.yml
Follow up of #298 
- Remove the deployment of arpeggio.
- Improve the additional services job: check that an additional service works properly only if it has been deployed.
=> fix: ci attempt 2

templates/trusted-node/cdk-node-config.toml
Changes needed to support latest changes in seq-sender.
=> Update to seq-sender no DS

docker/README.md
Add `-fork.12` suffix to the image names.
https://0xpolygon.slack.com/archives/C07AWFULS49/p1728355705224419?thread_ts=1727810820.042759&cid=C07AWFULS49
=> docs: update `leovct/zkevm-contracts` PP images tags

.github/workflows/nightly.yml
Related to #306 
- Failing job: https://github.com/0xPolygon/kurtosis-cdk/actions/runs/11340172599/job/31536137001
- Fixed job: https://github.com/leovct/kurtosis-cdk/actions/runs/11341395901/job/31539585345
=> ci: fix pless-zkevm-node cardona nightly job

docker/toolbox.Dockerfile, docker/zkevm-bridge-ui/zkevm-bridge-ui.Dockerfile, docker/zkevm-contracts.Dockerfile
- Remove `CGO_ENABLED=0` when building `polycli` (thx @minhd-vu for reporting it!)
- Bump images versiosn (alpine, ubuntu, node, npm).
- Download the latest version of foundry.
- Remove old comments.
x
=> chore: update Dockerfiles

docs/acl-allowlists-blocklists.md, docs/trustless-recovery-from-dac-l1.md
This PR adds docs for the `acl` command to be used within the Erigon sequencer.
=> docs: add docs for acl allowlist and blocklist

.github/workflows/security-build.yml
Follow up of #312
https://github.com/0xPolygon/kurtosis-cdk/actions/runs/11464275653
=> ci: fix security build job

.github/tests/combinations/fork11-legacy-zkevm-stack-rollup.yml, .github/tests/combinations/fork11-new-cdk-stack-cdk-validium.yml, .github/tests/combinations/fork11-new-cdk-stack-rollup.yml, .github/tests/combinations/fork12-new-cdk-stack-cdk-validium.yml, .github/tests/combinations/fork12-new-cdk-stack-rollup.yml, .github/tests/combinations/fork9-legacy-zkevm-stack-cdk-validium.yml, .github/tests/combinations/fork9-legacy-zkevm-stack-rollup.yml, .github/tests/combinations/fork9-new-cdk-stack-cdk-validium.yml, .github/tests/combinations/fork9-new-cdk-stack-rollup.yml, .github/tests/components/legacy-zkevm-stack.yml, .github/workflows/lint.yml
Make sure that the test combinations commited to this repository are up to date.
Follow up:
- ✅ Success: https://polygon.enterprise.slack.com/lists/T8VPLGV4Z/F07AWFULS49?record_id=Rec07TT5X68Q0
- ❌ Failure: https://github.com/0xPolygon/kurtosis-cdk/actions/runs/11476127934/job/31935459725?pr=330
- https://github.com/0xPolygon/kurtosis-cdk/actions/runs/11476033706/job/31935159077?pr=330
=> ci: test combinations check

.github/workflows/deploy.yml, input_parser.star, templates/cdk-erigon/config.yml, templates/trusted-node/cdk-node-config.toml
An attempt to simplify the cdk node configuration and reduce the tech debt.
Minor: upload enclave dump even when the workflow succeeds for debug purposes.
https://0xpolygon.slack.com/archives/C06B9L32F8E/p1729808871578009?thread_ts=1729794129.069409&cid=C06B9L32F8E
=> chore: simplify templates relying on fork id conditions

templates/contract-deploy/run-l2-contract-setup.sh
Switching to async calls for funding to speed up the l2 setup stage.
=> fix: speeding up some of the funding

scripts/.gitignore, scripts/datastreamer.toml, scripts/sanity-check.sh
- Adding fix for #342 
- Adding checks for the data stream timestamp
- Checking if the batch is closed before doing comparisons
- Removing some checks that will probably always fail
=> fix: minor fixes for the sanity check script

docker/README.md
- Add link to zkevm-contract image builder workflow.
- Clean up the docs.
- https://polygon.enterprise.slack.com/lists/T8VPLGV4Z/F07AWFULS49?record_id=Rec07V48FFZDF
=> docs: update docker docs

input_parser.star
Bumping the agglayer version and ensuring CIs are passing.
=> chore: agglayer version bump for ci process

templates/trusted-node/cdk-node-config.toml
=> fix: config file for node

static_files/additional_services/panoptichain-config/config.yml, templates/contract-deploy/run-contract-setup.sh
Should be a fix for #365. Tested locally with success.
=> fix: l1testing address to match input_parser value

input_parser.star, templates/bridge-infra/agglayer-config.toml
I'm bumping the version of the agglayer node and configuring the `genesis-block` parameter.
=> Agglayer Version Bump and Genesis Block Config

src/additional_services/panoptichain.star
=> chore: update panoptichain image

.github/workflows/test.yml, input_parser.star, templates/trusted-node/cdk-node-config.toml
- Remove agglayer db from the agglayer template.
- Bump cdk node to latest version.
=> feat: sqlite aggregator

src/additional_services/panoptichain.star
=> chore: panoptichain support pessimistic time since last verified

cdk_bridge_infra.star, input_parser.star, lib/zkevm_bridge.star, main.star
Make Bridge UI optional, and also add higher timeout for Bridge-UI port, because for some reason on the GHA I'm working on, it timed out waiting for Bridge-UI (and the timeout was not enough).
=> Bridge UI port wait + Bridge UI optional

docs/edit-contracts.md
**Fix Typo in `edit-contracts.md`**
This pull request fixes a typo in the `edit-contracts.md` documentation file to enhance clarity and accuracy.
- **File Modified:** `docs/edit-contracts.md`
- **Summary of Changes:**  
- Corrected the typo in the text from `coyping` to `copying`.
This change ensures the documentation is more professional and user-friendly for developers working with `kurtosis-cdk`.
---
**Allow edits by maintainers:** [x]
=> typo fix edit-contracts.md

.github/tests/agglayer-sp1-key.yml, .github/tests/attach-second-cdk-pessimistic.yml, .github/tests/attach-second-cdk.yml, .github/tests/attach-third-cdk.yml, .github/tests/fork12-pessimistic.yml, .github/workflows/deploy.yml, agglayer.star, docs/multi-pp-testing/lxly.pict, docs/multi-pp-testing/net1.yml, docs/multi-pp-testing/net2.yml, docs/multi-pp-testing/net3.yml, docs/multi-pp-testing/run.sh, docs/multi-pp-testing/test-scenarios.json, input_parser.star
=> AggLayer Version Update

docs/blockscout.md, input_parser.star, src/additional_services/blockscout.star
Add required optional params for Blockscout so it can be published without messing with .star files
=> Add blockscout params

.github/tests/chains/l1-cdk1-cdk2.yml, input_parser.star
This PR updates the SPN RPC endpoint + removes stale key
=> chore: change spn rpc

docker/README.md, docker/toolbox.Dockerfile, src/package_io/constants.star
Add bc, update versions, reduce image size
=> Add bc, update versions, reduce image size

.github/tests/nightly/pless-zkevm-node/cardona-sepolia-testnet-pless-zkevm-node.yml, docs/permissionless-zkevm-node.md
Closes #444 
https://github.com/leovct/kurtosis-cdk/actions/runs/13389491621/job/37393731888
=> docs: update zkevm pless doc

input_parser.star, main.star, src/additional_services/bridge_spammer.star, static_files/additional_services/bridge-spammer-config/spam.sh
Additional service: bridge_spammer that works same way than tx_spammer does
=> Add bridge spammer

input_parser.star
https://0xpolygon.slack.com/archives/C02JAJVVAH1/p1739953499497809
=> chore: reduce op participants count to one

.github/tests/combinations/fork11-cdk-erigon-rollup.yml, .github/tests/combinations/fork11-cdk-erigon-validium.yml, .github/tests/combinations/fork11-legacy-zkevm-rollup.yml, .github/tests/combinations/fork12-cdk-erigon-rollup.yml, .github/tests/combinations/fork12-cdk-erigon-sovereign.yml, .github/tests/combinations/fork12-cdk-erigon-validium.yml, .github/tests/combinations/fork13-cdk-erigon-rollup.yml, .github/tests/combinations/fork13-cdk-erigon-validium.yml, .github/tests/combinations/fork9-cdk-erigon-rollup.yml, .github/tests/combinations/fork9-cdk-erigon-validium.yml, .github/tests/combinations/fork9-legacy-zkevm-rollup.yml, .github/tests/combinations/fork9-legacy-zkevm-validium.yml, .github/tests/forks/fork11.yml, .github/tests/forks/fork12.yml, .github/tests/forks/fork13.yml, .github/tests/forks/fork9.yml, templates/contract-deploy/run-l2-contract-setup.sh
There was a race condition funding l2 accounts and deploying the determininistic proxy with the nonces.
- Closes #479
=> fix: deploying l2 contracts

input_parser.star, main.star, src/package_io/constants.star, templates/bridge-infra/agglayer-config.toml, templates/sovereign-rollup/sovereign-bridge-config.toml
Cleanup, check anvil args, set default consensus
=> Small changes for Anvil and OP check

create_sovereign_predeployed_genesis.star, deploy_zkevm_contracts.star, main.star, templates/sovereign-rollup/create-genesis-sovereign-params.json, templates/sovereign-rollup/create-predeployed-sovereign-genesis.sh, templates/sovereign-rollup/run-sovereign-setup.sh
Creates the Genesis file for OP including predeployed contracts, using tool from contracts team.
The genesis file is not used anywhere yet, just generated.
https://github.com/0xPolygonHermez/zkevm-contracts/tree/feature/ongoing-v0.3.0/tools/createSovereignGenesis
=> Genesis with predeployed contracts

src/additional_services/panoptichain.star
=> chore: use ghcr panoptichain image

templates/aggkit/aggkit-config.toml, templates/contract-deploy/run-contract-setup.sh
Quick fix to support latest contracts changes.
=> fix: issue with new format for create rollup output

create_sovereign_predeployed_genesis.star, input_parser.star, main.star, templates/sovereign-rollup/create-predeployed-sovereign-genesis.sh
Allow using custom optimism-package for custom deployment, like adding predeployed contracts to the OP genesis.
=> Add support for OP additional predeployed contracts

.github/tests/additional-services.yml, .gitignore, input_parser.star, main.star, src/additional_services/status_checker.star, static_files/additional_services/status-checker-config/check.sh, static_files/additional_services/status-checker/check.sh
Implement a small service that monitors the verification progress of zkEVM batches every 10 seconds. If one of the batch number is stuck for more than a minute, the service will log an error.
=> feat: status checker

static_files/additional_services/status-checker-config/check.sh
Related to #533 
Forgot to reset the counters... Lol
=> fix: status checker idle counter

lib/cdk_node.star, templates/cdk-erigon/config.yml
https://github.com/agglayer/aggkit/issues/296
=> support aggkit and cdk

.github/workflows/op-succinct-docker-image-builder.yml
- op-succinct docker image builder workflow to trigger, build, and push op-succinct images based on the specific agglayer/op-succinct repo's commit hash or branch
=> feat: add op-succint docker image builder

.github/workflows/deploy.yml
=> ci: improve readability of job names

README.md
Update service, port and artifact names.
Closes #552
=> docs: update faq

.github/tests/chains/op-succinct-real-prover.yml
Also, add `# XXX` comments to clearly mark the places people probably want to edit
=> feat: introduce a real-prover config file

README.md, docker/toolbox.Dockerfile, docker/zkevm-contracts.Dockerfile, docs/trigger-a-reorg/network-helper.Dockerfile
=> chore: update polygon-cli reference

input_parser.star
=> feat: bumpping agglayer version

.github/tests/chains/op-succinct.yml, input_parser.star
Unfortunately I still have not been able to get the e2e tests to pass in mock mode, even though all certificates seem to settle fine… will continue working on it next week 🥲
=> feat: aggkit-prover rc20 and bigger span proofs for mock mode too

input_parser.star
This PR updates the `aggkit_image` to a newer version.
=> chore: update aggkit image

.github/tests/additional-services.yml, input_parser.star, main.star, src/additional_services/launcher.star, src/additional_services/pless_zkevm_node.star, src/package_io/constants.star
- Implement an additional service launcher to simplify `main.star`.
- Implement a sanity check for additional services.
- Define additional services names in `constants.star`.
=> refactor: additional services launcher

.github/tests/additional-services.yml, main.star, src/additional_services/launcher.star, src/additional_services/test_runner.star, src/hex/hex.star, src/package_io/constants.star, src/wallet/wallet.star
Implement a new additional service called test runner that bundles our [agglayer/e2e](https://github.com/agglayer/e2e) tests.
=> feat: implement test runner

.github/actions/setup-kurtosis-cdk/action.yml, .github/workflows/deploy.yml, .github/workflows/docker-image-builder.yml, .github/workflows/lint.yml, .github/workflows/nightly.yml, .github/workflows/op-succinct-docker-image-builder.yml, .github/workflows/security-build.yml
- Pin tag for non-immutable actions.
- Add permissions.
https://github.com/0xPolygon/kurtosis-cdk/security/code-scanning
=> fix: workflows security issues

aggkit.star
- Add `deployment_suffix` to aggkit-prover service
=> chore: add deployment suffix to aggkit-prover

input_parser.star, src/additional_services/test_runner.star
Allow to customise the version of the test runner to deploy - very useful for antithesis testing.
Also update to the latest version.
=> feat: test runner image arg

templates/aggkit/aggkit-config.toml
Issue: https://github.com/agglayer/aggkit/issues/581
=> chore: add `UseTLS` in aggkit config 

static_files/additional_services/status-checker-config/checks/l2-coinbase.sh
- Ensures that the l2 coinbase on sequenceBatches event is called with the correct coinbase
- https://github.com/0xPolygon/devtools/issues/188
=> feat: l2 coinbase check

templates/aggkit/aggkit-config.toml
closes https://github.com/0xPolygon/kurtosis-cdk/issues/652
=> move MaxCertSize to the correct place

.github/workflows/kurtosis-deploy.yml, ethereum.star, input_parser.star, lib/op_succinct.star, templates/aggkit/aggkit-config.toml
- op-succinct-proposer
- aggkit
- l1 components: geth + lighthouse
- l2 components: op-geth + op-node + op-batcher
=> chore: standardize json logging format across services

input_parser.star, templates/bridge-infra/agglayer-config.toml
=> Setting `gas-multiplier-factor` and bumping versions

docker/README.md, docker/status-checker.Dockerfile, static_files/additional_services/status-checker-config/checks/l1-info-tree/main.sh
- Adds optional offline status-checker image
- Formats `docker/README.md`
- closes https://github.com/0xPolygon/devtools/issues/342
=> feat: offline status-checker image

static_files/additional_services/status-checker-config/checks/l1-info-tree/main.go, static_files/additional_services/status-checker-config/checks/l1-info-tree/main.sh
- Taking in an argument that's too long causes issues, take in a file instead
=> fix: l1 info tree status check buffer limit

input_parser.star, templates/aggkit/aggkit-config.toml
- Bump aggkit image version
- Document additional aggkit configs
=> chore: bump aggkit ver

.github/workflows/nightly.yml, docs/docs/version-matrix.md
=> docs: update version matrix

README.md
=> docs: fix old link

.github/workflows/nightly.yml
https://github.com/0xPolygon/kurtosis-cdk/actions/runs/17411395252
=> ci: fix typos in `nightly` workflow

deploy_agglayer_contracts.star
Dump kurtosis input args to JSON file, which will allow to check any param through contracts JSON API
=> Dump kurtosis input args to contracts image JSON file

lib/aggkit.star
Very small conceptual fixes to aggkit config strictly related to kurtosis
=> Persistend directory, conditional bridge port
