- main.star
- zkevm_permissionless_node.star
@tedim52 identified that some of our ineffeciencies were due to missing `name`s on each of our files.  In this PR I'm squashing and signing https://github.com/0xPolygon/kurtosis-cdk/pull/25 and also adding more more name. After making that change it looks like enclave edits are working!
> Enclave Editing

- README.org
- lib/service.star
- main.star
- params.yml
- templates/agglayer-config.toml
- templates/bridge-config.toml
- templates/dac-config.toml
- templates/run-contract-setup.sh
The deployment process is now divided into various stages. The `stages` parameter indicates the specific stages you wish the deployment to proceed through. By default, it will execute all the stages.
```bash
kurtosis clean -a
yq e '.stages = [1]' --inplace params.yml
kurtosis run --enclave cdk-v1 --args-file params.yml .
yq e '.stages = [2]' --inplace params.yml
kurtosis run --enclave cdk-v1 --args-file params.yml .
yq e '.stages = [3]' --inplace params.yml
kurtosis run --enclave cdk-v1 --args-file params.yml .
yq e '.stages = [4]' --inplace params.yml
kurtosis run --enclave cdk-v1 --args-file params.yml .
yq e '.stages = [5]' --inplace params.yml
kurtosis run --enclave cdk-v1 --args-file params.yml .
```
> refactor: break down the deployment process into various stages

- README.org
- docs/fork-id-migration.org
- main.star
- params.yml
This is mostly a documentation commit, but there are also some minor changes to the staged process that @leovct  put together in order to separate the creation of the database from the actual services starting. Those are now in stage 2.5.
> Fork ID Upgrading Notes

- .gitignore
- README.org
- docs/bridge-manual-claim.sh
- docs/gas-token.org
- Minor updates to the Gas Token docs.
- The manual bridge claim has been extracted to a script file. I think that's easier to execute as a user.
- The manual bridge can process multiple manual bridge claim at the same time now.
- Add troubleshooting doc for Mac users in the main README.
- Manually claim bridge transactions when:
> docs: gas token docs review

- .github/workflows/deploy.yml
- templates/run-contract-setup.sh
- Remove the hack as the [patch](https://github.com/0xPolygonHermez/zkevm-contracts/pull/226) as already been merged into `zkevm-contracts@develop`.
- Add a CI workflow to test the gas token feature.
> chore: remove contracts forge build hack

- .github/workflows/deploy.yml
- README.org
- deploy_zkevm_contracts.star
- docs/fork-id-migration.org
- docs/gas-token.org
- docs/zkevm-contracts-images-builder.sh
- docs/zkevm-contracts.Dockerfile
- params.yml
- templates/run-contract-setup.sh
- Build zkevm contracts images for both `linux/amd64` and `linux/arm64`, for fork ids 4, 5, 6, 7, 8 and 9. These images contain all the `npm` dependencies and the compiled contracts. They weight around 2GB and have a compressed size of around 700/900MB. The images are hosted on the [Docker Hub](https://hub.docker.com/r/leovct/zkevm-contracts/tags) under my username for now, but [we are planning to move them to GCR](https://polygon.atlassian.net/browse/DVT-1435) in the future.
- A README section has been added to explain how to build the images. The process is manual, you can either use a script or trigger a Github action [workflow](https://github.com/leovct/zkevm-contracts/actions/workflows/build-zkevm-contracts-images.yml).
- Update the contract deployment script by removing the …
> feat: zkevm contracts caching solution

- cdk_bridge_infra.star
- cdk_central_environment.star
- cdk_databases.star
- lib/service.star
- lib/zkevm_agglayer.star
- lib/zkevm_bridge.star
- lib/zkevm_dac.star
- lib/zkevm_databases.star
- lib/zkevm_node.star
- main.star
- observability.star
- params.yml
- zkevm_permissionless_node.star
Make use of `plan.add_services` to start components in parallel.
Previously, our libs would create each service individually, in a sequential manner. Now, they only create the service configs. It is then possible to aggregate all those service configs and to create them all at once, in parallel. It's not a significant change in speed (~20s less) but it cleans up the log. The flow is better now.
- Introduce `zkevm_agglayer`, `zkevm_bridge` and `zkevm_dac` libraries.
For the first run, use code from `main` and for the second run, use code from `feat/optimizations`.
- Clean the environment.
- Run only the L1 stages (L1 deployment + smart contract deployment).
- Run all the other stages, except the L1 stages and measure the time it takes to deploy the services.
First run …
> feat: start services in parallel

- README.org
The dev rel team faced a bunch of issues trying to run our Kurtosis package on macOS. Indeed, our `Troubleshooting for Mac Users` section is not very detailed. We are simply redirecting people to external documentation and people may miss crucial steps. In the end, their setup does not work... 
This PR addresses this problem by improving our docs with links to external documentation but also detailed steps including commands to run and expected outputs.
https://polygon.atlassian.net/browse/DVT-1440
> docs: update Troubleshooting for Mac Users section

- cdk_bridge_infra.star
- lib/zkevm_bridge.star
- params.yml
- Fix the zkevm RPC URL and the bridge API URL in the environment variables of the zkevm bridge ui (introduced in #45).
- Revert #59 because it breaks the setup on macOS - we need to find out a better way to handle those problems using a gateway/proxy in front of the zkevm-bridge-ui app.
> fix: zkevm-bridge-ui env

- cdk_bridge_infra.star
- lib/zkevm_bridge.star
- params.yml
- templates/bridge-infra/haproxy.cfg
This PR duplicates https://github.com/0xPolygon/kurtosis-cdk/pull/58 - the only difference is that I've also modified the bridge UI to support relative URLs which seems like it's going to be necessary. Either way there are some good benefits here:
- The "add to metamask" button works now. I think because we're not using HTTPS, but we are using 127.0.0.1 which is allowed
- This should fit within the kurtosis networking model and hopefully enables support for mac / wsl / etc
> feat: add reverse proxy to simplify zkevm-bridge-ui setup

- README.md
Clean up an old `.org` artifact.
Follow up of #64 that removed `README.org` in favor or `README.md`.
> docs: fix licenses links in `README.md`

- .github/workflows/deploy.yml
- .github/workflows/regression-tests.yml
- doc-drafts/fork-id-migration.org
- lib/zkevm_dac.star
- lib/zkevm_node.star
- params.yml
- Use the `main` branch instead of @rebelArtists's custom [branch](https://github.com/0xPolygon/kurtosis-cdk/compare/main...dan/jit_containers). This involves a bunch of changes:
- No need to clone the `kurtosis-cdk` repository and to checkout to a custom branch.
- The `zkevm-agglayer` docker image is now built using [Dockerfile.release](https://github.com/0xPolygon/agglayer/blob/main/Dockerfile.release) instead of [docker/Dockerfile](https://github.com/0xPolygon/agglayer/blob/main/docker/Dockerfile). Indeed, `Dockerfile.release` is used to build production images of the agglayer. Thus we don't need this fix anymore.
- Update `params.yml` to use local docker images.
- Bump actions versions.
- Log inputs values when the job is starting.
- Update regression check (logic is the same).
- …
> ci: update regression test job

- ethereum.star
- params.yml
- Enable to deploy L1 additional services via `params.yml`.
- Here is a quick example with:
- L1 block explorer (blockscout)
- L1 beaconchain explorer (dora)
- L1 fork/reorg monitor (forkmon)
```yaml
args:
l1_additional_services: [
blockscout, # block explorer
dora, # beaconchain explorer
el_forkmon, # fork monitor tool
]
```
> feat: enable to deploy l1 additional services

- docs/quickstart/connect-testnet.md
- mkdocs.yml
This PR adds the How to menu and the testnet doc to align with main site.
> docs: restructure menu to fit with main site

- docs/how-to/quick-test-stack.md
- docs/index.md
This PR fixes a code block error and rewords the introductory page a little.
> docs: code block fix and some rewording

- deploy_zkevm_contracts.star
The contract service will run in a pod in Kubernetes. Unfortunately, there is no command specified when starting the service, thus [the pod will terminate](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#container-state-terminated) just after startup. As we need this service to be available later in the deployment, we simply add an infinite loop to trick Kubernetes so that the pod [stays alive](https://www.youtube.com/watch?v=I_izvAbhExY&ab_channel=beegees). This has no impact on Docker deployments.
> fix: kubernetes deployment

- docs/how-to/migrate/fork.md
- mkdocs.yml
This PR adds the general instructions for partners back in which went missing for a while: https://github.com/0xPolygon/polygon-docs/pull/326/files
> docs: add general migration guide back in

- .github/ISSUE_TEMPLATE/bug_report.yml
- scripts/tool_check.sh
Update the tool check script to make sure users have installed the required versions of kurtosis and docker. It is easy to have the wrong combination of versions, which unfortunately makes our package unusable...
This PR also updates the bug report template to ask users to run the tool check script.
Before updating kurtosis to the latest version...
```bash
$ ./scripts/tool_check.sh
Checking that you have the necessary tools to deploy the Kurtosis CDK package...
❌ kurtosis 0.88.19 is installed, but only version 0.89 is supported.
```
After updating kurtosis...
```bash
$ ./scripts/tool_check.sh
Checking that you have the necessary tools to deploy the Kurtosis CDK package...
✅ kurtosis 0.89.3 is installed, meets the requirement (=0.89).
✅ docker 26.0.0 is installed, meets the requirement …
```
> chore: update tool check script

- .github/workflows/deploy.yml
- blockscout.star
- docs/quickstart/breakdown-deployment.md
- input_parser.star
- kurtosis.yml
- main.star
- observability.star
- params.yml
That should make Blockscout  work on MAC as well, by using a public_port since that can't be achieved through a proxy though.
It also fixes/improves some configurations, remove ads, etc.
Now Blockscout is disabled by default, you need to enable it on params.yaml or just on command line:
`kurtosis run . '{"deploy_blockscout":true}'`
> Set public port for Blockscot

- docs/quickstart/breakdown-deployment.md
The https://docs.polygon.technology/cdk/get-started/quickstart/breakdown-deployment/#deploy-cdk-bridge-infrastructure docs is spinning up the permissionless node.
I added the correct parameter.
Issue raised by user: https://github.com/0xPolygon/polygon-docs/discussions/390#discussioncomment-9504165
> docs: typo in script

- .github/workflows/deploy.yml
- .gitignore
- cdk_central_environment.star
- deploy_zkevm_contracts.star
- doc-drafts/da-mode.md
- docs/how-to/migrate/forkid-7-to-9.md
- input_parser.star
- kurtosis.yml
- lib/data_availability.star
- lib/service.star
- lib/zkevm_node.star
- params.yml
- scripts/compare_default_params.sh
- templates/contract-deploy/run-contract-setup.sh
Introduce a new parameter `data_availability_mode` in `params.yml` to specify the type of data availability to use.
The two options are:
- `rollup`: Transaction data is stored on-chain on L1.
> In this mode, the components will run the `zkevm_node_image` and the consensus contract will be `PolygonZkEVMEtrog`.
- `validium`: Transaction data is stored off-chain using a DA layer and a DAC. 
> In this mode, the components will run the `cdk_node_image`, the consensus contract will be `PolygonValidiumEtrog` and the DAC will be deployed and configured.
Also two new CI jobs `rollup-da-mode` and `validium-da-mode` and a doc regarding da-modes have been added
- https://polygon.atlassian.net/browse/DVT-1518
- Closes https://github.com/0xPolygon/kurtosis-cdk/issues/117
> feat: introduce data availability mode

- .github/workflows/docker-image-builder-cron.yml
This workflow should only run on the main repository. On top of that, the jobs will fail on forks because `DOCKERHUB_USERNAME` and `DOCKERHUB_PASSWORD` will not be defined.
https://github.com/leovct/kurtosis-cdk/actions/runs/9345127975
> ci: prevent docker image builder cron job to run on forks

- .github/workflows/deploy.yml
- .github/workflows/security-build.yml
Introduce an `authorize` job that allows code maintainers to approve a pull request to use the GitHub Action secrets. This ensures that any job requiring secrets can function for both internal and external PRs.
This is a test implementation and should only be applied to the security build job for now. If it proves successful, we will extend it to the deploy job, which also requires secret access.
https://dvc.ai/blog/testing-external-contributions-using-github-actions-secrets
> ci: fix external contributors pr failures

- .github/workflows/deploy.yml
Introduce an `authorize` job that allows code maintainers to approve a pull request to use the GitHub Action secrets. This ensures that any job requiring secrets can function for both internal and external PRs.
A test has already been done with the Security Build job. It worked well (#139). We now do the same for the `deploy` workflow which requires secret access to get the RPC URL.
Follow up of #139
> ci: prevent `permisionless-node` job to fail on forks

- .github/workflows/deploy.yml
Follow up of #143. The problem is that the workflow runs in the context of the `main` branch, which means it executes the workflow code, environment, and configurations from the `main` branch, not the changes introduced in the pull request branch. This pull request aims to modify the workflow to run against the code and changes present in the pull request branch, rather than the `main` branch context.
- https://dvc.ai/blog/testing-external-contributions-using-github-actions-secrets
- https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target
> ci: run `deploy` workflow against branch

- ethereum.star
fix ethereum.star dependency which is breaking all local kurtosis-cdk runs. the ethpandaops package appears unstable..
current error logs, which are resolved by the package switch in this PR: 
`root@dan-cdk-tests:~/kurtosis-cdk# kurtosis run --enclave cdk-v1 --args-file cdk-erigon-sequencer-params.yml --image-download always .
INFO[2024-06-20T19:20:22Z] Engine running in Kubernetes cluster, to connect to the engine from outside the cluster run 'kurtosis gateway' to open a local gateway to the engine 
INFO[2024-06-20T19:20:22Z] Creating a new enclave for Starlark to run inside... 
INFO[2024-06-20T19:20:43Z] Enclave 'cdk-v1' created successfully        
INFO[2024-06-20T19:20:43Z] Executing Starlark package at '/root/kurtosis-cdk' as the passed argument '.' looks like a directory …
> [bug] fix eth star dependency

- mkdocs.yml
Updating the polyfill.io to use the cloudflare provided service for some security concerns. 
https://thehackernews.com/2024/06/over-110000-websites-affected-by.html
https://blog.cloudflare.com/polyfill-io-now-available-on-cdnjs-reduce-your-supply-chain-risk
> Updating polyfill service url

- lib/service.star
cdk-erigon should mandate the admin contract address be in config (fixed here: https://github.com/0xPolygonHermez/cdk-erigon/pull/673).
PR which enforces the requirement in cdk-erigon: https://github.com/0xPolygonHermez/cdk-erigon/pull/673
> fix(cdk-erigon): add admin contract addr

- templates/permissionless-node/node-config.toml
This config change fixes permissionless nodes not being able to reach the sequencer when deploying multiple permissionless nodes with varying suffixes by inferring the sequencer address from the smart contract directly.
> fix: config for sequencer uri on permissionless node

- README.md
Replacing the devs discord link with the RnD discord.
> docs: update R&D discord link

- .github/workflows/security-build.yml
Follow up of #175.
- Switch back to `pull_request` trigger and remove `authorize` job from the security workflow.
- Bump `actions/checkout` version.
> ci: fix security workflow

- .github/actions/monitor-cdk-verified-batches/batch_verification_monitor.sh
Improve the readability of logs.
For reference: https://github.com/0xPolygon/kurtosis-cdk/actions/runs/10192893388/job/28196535749#step:5:11
x
> ci: hide `cast send` output in `batch_verification_monitor.sh`

- docker/toolbox.Dockerfile
- docker/zkevm-contracts.Dockerfile
- Sort packages in `apt-get install` command to fix the security issue.
- Also sort the flags in the same command for readability.
https://github.com/0xPolygon/kurtosis-cdk/security/code-scanning/13
> chore: sort packages and flags in `apt-get install` commands

- templates/cdk-erigon/config.yml
Remove the `zkevm.sequencer-non-empty-batch-seal-time` from configuration, since that flag got obsoleted through the [PR](https://github.com/0xPolygonHermez/cdk-erigon/pull/909) on the CDK Erigon.
- https://github.com/0xPolygonHermez/cdk-erigon/pull/909/files#diff-7aa83061ca1c69a8ab9203da49a7581bad6e7cc80ecb96582e7fb09c0b8f6534L474-L477
> Remove `zkevm.sequencer-non-empty-batch-seal-time` from config

- .gitignore
- scripts/compare_default_params.sh
New output:
```bash
Extracting default parameters from input_parser.star...
Extracting default parameters from kurtosis.yml...
Extracting default parameters from params.yml...
🔍 Comparing .params.yml and .input_parser.star...
3 differences found:
📄 .params.yml (source of truth)
--------------------------------------------------------------------------------
zkevm_sequence_sender_image: hermeznetwork/zkevm-sequence-sender:v0.2.0-RC5
cdk_erigon_node_image: hermeznetwork/cdk-erigon:2.0.0-beta16
toolbox_image: leovct/toolbox:0.0.2
📄 .input_parser.star (🚨 to be updated 🚨)
--------------------------------------------------------------------------------
zkevm_sequence_sender_image: hermeznetwork/zkevm-sequence-sender:v0.2.0-RC4
cdk_erigon_node_image: hermeznetwork/cdk-erigon:2.0.0-beta15 …
```
> chore: enhance readability of `compare_default_params.sh` script output

- README.md
Fix the command to deploy the legacy stack (zkevm-node).
> docs: fix the command to deploy the legacy stack in `README`

- .github/scripts/compare-default-params.sh
- .github/workflows/lint.yml
- agglayer-attach-cdk-params.yml
- cdk_bridge_infra.star
- cdk_central_environment.star
- input_parser.star
- kurtosis.yml
- lib/zkevm_sequence_sender.star
- params.yml
- src/additional_services/tx_spammer.star
- src/package_io/constants.star
- static_files/additional_services/panoptichain-config/config.yml
- templates/bridge-infra/agglayer-config.toml
- templates/bridge-infra/bridge-config.toml
- templates/cdk-erigon/config.yml
- templates/permissionless-node/node-config.toml
- templates/pool-manager/pool-manager-config.toml
- templates/trusted-node/cdk-node-config.toml
- templates/trusted-node/dac-config.toml
- templates/trusted-node/node-config.toml
- templates/trusted-node/sequence-sender-config.toml
Configure `args.global_log_level` to specify the log level for all components of the CDK stack.
Valid values are `error`, `warn`, `info`, `debug` and `trace`.
Also few fixes related to default params (not related to this PR).
```bash
$ kurtosis service logs cdk-v1 cdk-erigon-node-001 --follow
[cdk-erigon-node-001] [INFO] [08-21|08:29:30.820] [16/16 Finish] Finished 
[cdk-erigon-node-001] [INFO] [08-21|08:29:30.850] Commit cycle                             in=30.608833ms
[cdk-erigon-node-001] [INFO] [08-21|08:29:30.850] Timings (slower than 50ms)               Batches=12.133s
[cdk-erigon-node-001] [INFO] [08-21|08:29:30.850] Tables                                   PlainState=20.0KB AccountChangeSet=12.0KB StorageChangeSet=36.0KB BlockTransaction=4.0KB TransactionLog=4.0KB FreeList=4.0KB …
```
> feat: add global log level parameter

- .github/workflows/deploy.yml
- main.star
- params.yml
Deploy panoptichain before prometheus so that prometheus can scrape panoptichain metrics!
- https://github.com/0xPolygon/kurtosis-cdk/actions/runs/10489071251/job/29052883683?pr=233#step:8:35
- #233
> fix: panoptichain deployment

- .github/workflows/deploy.yml
- cdk_bridge_infra.star
- cdk_central_environment.star
- databases.star
- main.star
- src/additional_services/pless_zkevm_node.star
- zkevm_pool_manager.star
I’ve noticed that deploying the `cdk` environment creates the various zkevm-node databases (state, pool and event) that aren’t needed. I suspect that other useless databases are being deployed.
We should first understand exactly which dbs are needed in which environment (`cdk` and `zkevm`) and then update the kurtosis implementation to reflect this.
> chore: streamline dbs deployment

- README.md
Specifying `--args-file <FILE>` with additional parameters `"{"args": ...}` in `kurtosis run` does not work well at all. Kurtosis does not take into account the arg file in this specific scenario...
> docs: fix `kurtosis run` commands

- README.md
We should take a stance and warn users against using kurtosis-cdk in production.
https://github.com/0xPolygon/kurtosis-cdk/issues/55#issuecomment-2058132893
> docs: define kurtosis-cdk as a dev tool meant for testing

- lib/cdk_erigon.star
This will be useful when we want to manually stop the process of cdk-erigon sequencer or rpc node for debugging purpose.
> Keep cdk-erigon container running even when cdk-erigon is killed

- templates/trusted-node/prover-config.json
This is required when using the latest prover (`8.0.0-RC8`).
> Disable state manager in prover when stateless executor is enabled

- .github/workflows/security-build.yml
Pull Requests from external forks consistently fail to pass all checks, even when the code itself is sound. This occurs due to the SonarCloud job, which requires access to the `SONAR_TOKEN` secret. For security reasons, PRs from external forks are not granted access to these secrets.
To address this issue, the SonarCloud job is now disabled for all pull requests.
Note that the SonarCloud analysis still runs when a PR is merged into the `main` branch.
https://github.com/0xPolygon/kurtosis-cdk/actions/runs/10810376967/job/29987498052
> ci: remove sonar cloud from pull request workflows

- .github/tests/forks/fork12.yml
- agglayer-attach-cdk-params.yml
- docker/README.md
- input_parser.star
- params.yml
- Bump to the latest fork12 release candidate (RC3)
- Deprecate the fix image `leovct/zkevm-contracts:feature-verified-number-e2ef9ca-fork.12`
https://0xpolygon.slack.com/archives/C06B9L32F8E/p1726414456959479?thread_ts=1725917291.255009&cid=C06B9L32F8E
> chore: bump zkevm contracts to `v8.0.0-rc.3-fork.12`

- agglayer-attach-cdk-params.yml
- input_parser.star
- params.yml
While testing the Access List feature in `cdk-erigon`, we encountered couple of bugs that were fixed and merged. In order to e2e test it, we need to update the `cdk-erigon` image that we use in kurtosis.
[JIRA Ticket](https://polygon.atlassian.net/browse/CDK-477?atlOrigin=eyJpIjoiNGVjYjAyOWM1NDg1NDc2M2JjZDVhMjQ1N2UwYjBmNjEiLCJwIjoiaiJ9)
> fix: update cdk erigon image

- .github/tests/pless-zkevm-node/cardona-sepolia-testnet-pless-zkevm-node.yml
#262 updated the agglayer implementation and moved the `deploy_agglayer` parameter outside of the `args` struct. It should be set to `false ` in the Cardona/Sepolia permissionless zkevm-node test.
✅ CI passes with the fix: https://github.com/leovct/kurtosis-cdk/actions/runs/10901640039
> fix: nightly job

- templates/contract-deploy/run-contract-setup.sh
This PR fixes the issue with `gasTokenAddress` not being populated in the `create_rollup_parameters.json`. It is due to the misplace of copying the `create_rollup_parameters.json` file contents with outdated values. The issue was introduced through #266.
> fix: Remove redundant copy step for `create_rollup_parameters.json`

- templates/trusted-node/cdk-node-config.toml
Sometimes synchronization db for aggregator raise errors like: 
```
FATAL	internal/synchronizer_impl.go:280	networkID: 0, error getting lastBlockSynced to resume the synchronization... Error: %!(EXTRA *fmt.wrapError=storage error: GetLastBlock: Err: no such table: block, string=
```
> fix: Sometimes fails synchronization db for aggregator

- input_parser.star
- params.yml
This is a small change to move away from the @cffls branded erigon images to the official builds from the CI. The change shouldn't impact anything else.
> chore: bumping to latest version of cdk-erigon

- .github/workflows/deploy.yml
Dump enclave state and logs if the CI fails for whatever reason. This will give us a clearer picture of the CI problems we have seen in recent weeks.
- Make the CI fail on purpose: https://github.com/0xPolygon/kurtosis-cdk/actions/runs/11128355637/job/30922907780?pr=292#step:10:22
- Download the kurtosis artifact
- List files
```bash
$ ~/Downloads > unzip -l dump_run_without_args_11128355637.zip
Archive:  dump_run_without_args_11128355637.zip
Length      Date    Time    Name
---------  ---------- -----   ----
15527  10-01-2024 15:29   enclaves/cdk--7b95aeb759c44f0388989146fddccd67/agglayer--2e8b551b6fea4b43925182103db899ee/output.log
9208  10-01-2024 15:29   enclaves/cdk--7b95aeb759c44f0388989146fddccd67/agglayer--2e8b551b6fea4b43925182103db899ee/spec.json
231641  10-01-2024 15:29 …
```
> ci: dump enclave state and logs on ci failures

- .github/scripts/compare-default-params.sh
- .github/tests/forks/fork11.yml
- .github/tests/forks/fork12.yml
- .github/tests/forks/fork9.yml
- .github/tests/pless-zkevm-node/cardona-sepolia-testnet-pless-zkevm-node.yml
- .github/workflows/deploy.yml
- .github/workflows/lint.yml
- input_parser.star
- params.yml
- Bump to latest versions of zkevm-prover, cdk-erigon and zkevm-node in the different tests fork 9, 11 and 12.
- Fix log dump with test matrix.
> ci: bump versions in tests

- README.md
- docs/deploy-using-sepolia.org
- input_parser.star
- lib/cdk_erigon.star
- scripts/sanity-check.sh
- static_files/additional_services/tx-spammer-config/bridge.sh
- static_files/additional_services/tx-spammer-config/spam.sh
- templates/cdk-erigon/config.yml
There are a few unrelated changes in this PR:
- Hopefully a fix for #309 which comes down to issues with the configuration with Erigon vs the Legacy Node
- Minor README changes for clarity based on some user feedback
- Version bumps for cdk-erigon and the cdk node
- Fixes related to pprof being broken and always failing to do CPU Profiles
- CI Reliability fixes to use different keys for the tx spammer
- Configuration fix to avoid using full witness by default
> Sepolia Deployment Doc Update and Version Bumps

- agglayer.star
- docs/attach-multiple-cdks.md
- input_parser.star
- templates/bridge-infra/agglayer-config.toml
- templates/bridge-infra/agglayer-prover-config.toml
Integrate the new `agglayer` and `agglayer-prover` into kurtosis
> feature: adding agglayer-prover

- input_parser.star
- templates/trusted-node/cdk-node-config.toml
Config changes to accomodate version 0.4.0 of CDK
Reference PR in CDK: https://github.com/0xPolygon/cdk/pull/138
> feat: update to CDK 0.4.0

- src/additional_services/tx_spammer.star
- static_files/additional_services/tx-spammer-config/bridge.sh
Prevent nonce issues when using the tx spammer in addition to the monitor script that already sends transactions using the admin private key.
https://github.com/0xPolygon/kurtosis-cdk/actions/runs/11552813017/job/32152686869?pr=335
> fix: use different private key to send loadtest from the tx spammer service

- docs/deterministic-deployment-proxy.md
- docs/native-token/native-token.md
- input_parser.star
By using the same mnemonic as the ethereum package, we avoid deriving 22 addresses and private keys.
The key derivation process used in the Ethereum package cannot be easily accelerated, as it involves creating an array from the output of a command (a string). This task is not trivial, which is why they opted for this method. Yes, it is a little inefficient, but at least it works in a Starlark environment.
- https://github.com/ethpandaops/ethereum-package/blob/main/main.star#L93-L99
- https://github.com/ethpandaops/ethereum-package/blob/main/src/package_io/constants.star#L99
> chore: speed up ethereum-pkg deployment by using the default mnemonic

- .github/workflows/deploy.yml
Make sure logs are uploaded when the workflow fails or succeeds while also making sure workflows are cancelable.
Tested in #339
> ci: fix log upload

- README.md
Add FAQ section to the README.
- Different ways to deploy the package.
- How to deploy to Kubernetes.
- How to debug issues with Kurtosis / Docker.
- How to debug in Kurtosis.
- How to lint the code.
- Links to the Kurtosis doc and the Starlark language spec.
https://polygon.enterprise.slack.com/lists/T8VPLGV4Z/F07AWFULS49?record_id=Rec07U1A2HREZ
> docs: add faq section

- .github/tests/combinations/fork13-new-cdk-stack-cdk-validium.yml
- .github/tests/combinations/fork13-new-cdk-stack-rollup.yml
- .github/tests/forks/fork13.yml
- input_parser.star
Bumping to the latest versions. This is especially important for fork 12 testing because the counter limits get adjusted.
> chore: bumping versions

- .github/actions/setup-kurtosis-cdk/action.yml
Bump from `1.0.0` to `1.4.1`.
- https://github.com/kurtosis-tech/kurtosis/releases/tag/v1.4.1
> ci: bump kurtosis version to `1.4.1`

- scripts/sanity-check.sh
The sanity check script should return an error when the `cdk` enclave does not exist.
Related to #347
> fix: sanity check script now returns an error when the cdk enclave does not exist

- .github/tests/combinations/fork11-legacy-zkevm-stack-rollup.yml
- .github/tests/combinations/fork11-new-cdk-stack-cdk-validium.yml
- .github/tests/combinations/fork11-new-cdk-stack-rollup.yml
- .github/tests/combinations/fork12-new-cdk-stack-cdk-validium.yml
- .github/tests/combinations/fork12-new-cdk-stack-rollup.yml
- .github/tests/combinations/fork9-legacy-zkevm-stack-cdk-validium.yml
- .github/tests/combinations/fork9-legacy-zkevm-stack-rollup.yml
- .github/tests/combinations/fork9-new-cdk-stack-cdk-validium.yml
- .github/tests/combinations/fork9-new-cdk-stack-rollup.yml
- .github/tests/forks/fork11.yml
- .github/tests/forks/fork12.yml
- .github/tests/forks/fork9.yml
> chore: bump cdk-erigon for <= fork12

- .github/workflows/docker-image-builder.yml
- docker/README.md
- Move the automated docker build workflow from my zkevm-contracts fork to the kurtosis-cdk repository.
- Update the `docker` docs.
The tests have been performed on my [fork](https://github.com/leovct/kurtosis-cdk) of the kurtosis-cdk repository. They required the creation of two new secrets, `IMAGE_BUILDER_DOCKERHUB_USERNAME` and `IMAGE_BUILDER_DOCKERHUB_TOKEN`.
1. Build and push images that already exist on the Docker Hub.
The workflow should skip the build and push part.
2. Build and push images that don't exist on the Docker Hub.
The workflow should push the images to the Docker Hub.
- Follow up of #351.
- https://polygon.enterprise.slack.com/lists/T8VPLGV4Z/F07AWFULS49?record_id=Rec07V48FFZDF
> ci: zkevm contracts docker image builder

- .github/tests/combinations/fork11-legacy-zkevm-stack-rollup.yml
- .github/tests/combinations/fork11-new-cdk-stack-cdk-validium.yml
- .github/tests/combinations/fork11-new-cdk-stack-rollup.yml
- .github/tests/combinations/fork12-new-cdk-stack-cdk-validium.yml
- .github/tests/combinations/fork12-new-cdk-stack-rollup.yml
- .github/tests/combinations/fork13-new-cdk-stack-cdk-validium.yml
- .github/tests/combinations/fork13-new-cdk-stack-rollup.yml
- .github/tests/combinations/fork9-legacy-zkevm-stack-cdk-validium.yml
- .github/tests/combinations/fork9-legacy-zkevm-stack-rollup.yml
- .github/tests/combinations/fork9-new-cdk-stack-cdk-validium.yml
- .github/tests/combinations/fork9-new-cdk-stack-rollup.yml
- .github/tests/forks/fork11.yml
- .github/tests/forks/fork12.yml
- .github/tests/forks/fork13.yml
- .github/tests/forks/fork9.yml
- input_parser.star
- templates/contract-deploy/deploy_parameters.json
There are three small changes here:
1. I'm disabling the l2 deployment process by default. This should speed things up slightly. But I'm keeping it in place for CI since it can help detect errors
2. I changing the default timelock delay to better support upgrade testing
3. I'm bumping to the latest cdk version.
> Enabling L2 Deployment for CI Tests Only

- input_parser.star
It seems like something has gone wrong with the bridge ui image recently in #363 
In testing, switching to the older image working (but slower). So we can fix this for now and repair the original image later.
> Temporarily change bridge ui default image

- input_parser.star
- main.star
- src/package_io/constants.star
The goal of this PR is to be able to deploy an enclave without exposing secrets stored in `args`.
The `args` struct should not be logged by default. It should only be logged if the `verbosity` flag is set to `debug` or `trace`, by default it is set to `info`.
Before
After
> feat: deploy without exposing secrets stored in `args`

- docker/README.md
- docker/zkevm-bridge-ui/deploy.sh.diff
- docker/zkevm-bridge-ui/zkevm-bridge-ui.Dockerfile
Revert most of the zkevm-bridge-ui changes made in #333.
We tried to speed up the zkevm-bridge-ui startup process by building the app directly in the `Dockerfile`. Unfortunately, this solution doesn't work because [Vite replaces environment variables at build time and not run time](https://github.com/vitejs/vite/issues/10059). This explains why the bridge UI complains about environment variables being not defined.
- Related to #363
> revert: zkevm-bridge-ui image changes

- input_parser.star
- templates/trusted-node/cdk-node-config.toml
While deploying the stack on external L1s like Sepolia using kurtosis-cdk, some users noticed that the cdk node was syncing from genesis instead of syncing from the rollup manager deployment block. It turns out the cdk node configuration is a bit outdated. Some settings are not set, instead, we rely on default values. For example, the L1 InfoTreeSync initial block is set to zero by default which explains why the cdk node syncs from the genesis block. This PR addresses this specific issue.
- Minor: Simplify the way contract versions is set in the config.
- Next steps: update and document the cdk node configuration.
https://discord.com/channels/893151281848406016/1306202853244665867/1306593102902857780
> fix: cdk node l1infotree sync configuration

- .github/workflows/cdk-e2e.yml
This PR introduces an extra github workflow `cdk-e2e.yml` which tests the e2e tests in the [cdk](https://github.com/0xPolygon/cdk/tree/main/test) repository. It includes the below matrix for testing.
```
- "fork9-validium"
- "fork11-rollup"
- "fork12-validium"
- "fork12-rollup"
```
> tests: integrate cdk bats test ci to kurtosis-cdk

- README.md
Document the issue when trying to run kurtosis on a mac and it fails to pull the zkevm-prover image.
```bash
Error response from daemon: no matching manifest for linux/arm64/v8 in the manifest list entries: no match for platform in manifest: not found
```
https://polygon.enterprise.slack.com/lists/T8VPLGV4Z/F07AWFULS49?record_id=Rec07V1G7R207
> docs: document issue with zkevm-prover and kurtosis on mac

- templates/bridge-infra/bridge-config.toml
when using a custom Sepolia chain, the data is not being stored in the database during the Deposit function on the Pessimistic Proof. That’s the reason for not working the Deposit functionality
> fix: set GenBlockNumber to rollup manager block number in bridge service config

- docs/resequence-sequencer/resequence-sequencer.md
- docs/resequence-sequencer/test_resequence.sh
- docs/timelock.org
- static_files/additional_services/tx-spammer-config/bridge.sh
- static_files/additional_services/tx-spammer-config/spam.sh
Use `cast --json` instead of `cast -j`.
- https://github.com/foundry-rs/foundry/pull/9367
> chore: update cast `-j` flag

- .github/workflows/deploy.yml
- docs/migrate/forkid-7-to-9.md
- templates/contract-deploy/run-contract-setup.sh
An attempt to fix the issue with the pre-deployed gas token workflow.
- Workflow issue: https://github.com/0xPolygon/kurtosis-cdk/actions/runs/12065490712/job/33644369491?pr=402
- Breaking change in `foundry create`: https://github.com/foundry-rs/foundry/pull/9420
> fix: pre-deployed gas token workflow

- README.md
After playing a little with kurtosis-cdk and the different ways to specify args, I noticed a weird behaviour when combining params file and on-the-fly args.
It was not properly documented so this PR fixes that.
- https://github.com/0xPolygon/leovct/blob/main/debug/kurtosis-cdk/params/params.md
> docs: update deploy section

- ethereum.star
The CL of the ethereum-package does not start because of an error. It looks like the `lighthouse` custom image used by the ethereum-package has been updated and thus it breaks previous versions of the package that rely on an old flag.
```bash
== SERVICE 'cl-1-lighthouse-geth' LOGS ===================================
error: unexpected argument '--http-allow-sync-stalled' found
tip: a similar argument exists: '--http-allow-origin'
Usage: lighthouse beacon_node --execution-endpoint <EXECUTION-ENDPOINT> --debug-level <LEVEL> --datadir <DIR> --disable-enr-auto-update --enr-address <ADDRESS>... --enr-udp-port <PORT> --enr-tcp-port <PORT> --listen-address [<ADDRESS>...] --port <PORT> --http-address <ADDRESS> --http-port <PORT> --http-allow-origin <ORIGIN> <--http|--gui|--staking>
For more …
```
> fix: bump ethereum-package to `v4.4.0`

- ethereum.star
Follow up of #409 which fixes the issue with the upstream ethereum-package but does not prevent us from potential breaking changes in the EL/CL images in the future. This PR pins the versions of the ethereum-package images.
#409
> fix: tag ethereum-package image versions

- .github/tests/fork12-pessimistic.yml
- src/additional_services/prometheus.star
Make sure a new Prometheus image doesn't break our package in any way.
Minor: fix an issue with the cdk node fork12 pp test:
> chore: pin prometheus image version

- .github/actions/setup-kurtosis-cdk/action.yml
Add flag -y to kursosis install command.
Trying to run action on custom docker image which already has kurtosis latest version installed fails because this flag is missing.
> Add -y flag to kurtosis install gha

- docker/README.md
- docker/toolbox.Dockerfile
- docker/zkevm-contracts.Dockerfile
Update our docker images to follow the new `foundryup` API.
Closes #431
> fix: docker images

- .github/workflows/lint.yml
- scripts/README.md
- scripts/upgrade_forkid.sh
Script to test the process of upgrading network forkid. Supported upgrades:
- 12 to 13
- 11 to 12
- 11 to 13
- 9 to 11
- 9 to 12
- 9 to 13
The script already deploys the kurtosis enclave, so it can NOT be applied to an existing enclave.
From the root of the repo, run:
`./scripts/upgrade_forkid.sh <source_forkid> <target_forkid>`
Example:
`./scripts/upgrade_forkid.sh 11 13`
> Upgrade forkid script

- .github/workflows/deploy.yml
The `deploy` workflow is running twice each job :)
^ 51 checks 🤯
> ci: fix `deploy` workflow

- input_parser.star
- main.star
There are some combinations of parameters within `input_parser.star` which can result in a successful deployment after running `kurtosis run .`, but may cause some services to fail after the deployment. An example of this would be:
```
"deploy_optimism_rollup": True,
...
"consensus_contract_type": "cdk-validium",
```
When running Kurtosis CDK with these parameters, the deployment will succeed, but the aggkit component will return an error, because the process of creating and attaching sovereign rollups and deploying sovereign contracts assumes a pessimistic consensus contract is supported.
This PR adds a helper function `sanity_check()` to check for these type of incompatible parameters at the start of the deployment and exits the deployment with `fail()` if such cases are caught. A …
> feat: add helper function for sanity checking parameters

- input_parser.star
This PR changes the `l1_seconds_per_slot` variable from `1` second to `2` seconds. This is to make sure that if the `deploy_optimism_rollup` parameter is set to `true`, it will not break the OP network even after long-running it. 
`2` seconds was chosen in particular because this is also the default blocktime for the OP network, and this is the fastest L1 blocktime that can be used without breaking anything when OP rollup is deployed. As a reference, if we do not specify the `l1_seconds_per_slot`, the current default setup will use `6` seconds, which is the default L1 blocktime for the `minimal` preset.
In cases where the OP rollup's blocktime is customized to `>2 seconds`, the L1 blocktime will also need to change to be greater or equal to it. 
---
Some [relevant …
> fix: change l1_seconds_per_slot from 1s -> 2s 

- .github/tests/op-rollup/custom.yml
- input_parser.star
Newly tagged OP-Geth and OP-Node images have been released which seems to fix deployment issues. This PR updates our images to this fixed tag.
https://us-docker.pkg.dev/oplabs-tools-artifacts/images/op-geth:v1.101500.0-rc.3
https://us-docker.pkg.dev/oplabs-tools-artifacts/images/op-node:v1.11.0-rc.2
> fix: update op images with official tags

- templates/contract-deploy/create-keystores.sh
Featureless PR that just speed ups keystore creation by using cast instead polycli.
The whole kurtosis deployment (default - no params) takes 3:45-3:49 instead 4-4:02, because create-keystores.sh takes ~12-13s using polycli and less than a second with cast.
> Create keystores with cast instead polycli

- aggkit.star
- agglayer.star
- cdk_bridge_infra.star
- cdk_central_environment.star
- docs/mitm.md
- input_parser.star
- main.star
- mitm.star
By setting any of these to True, mitm will be deployed and the component/s will be configured with mitm as L1 endpoint.
```
"mitm_proxied_components": {
"agglayer": False,
"aggkit": False,
"bridge": False,
"dac": False,
"erigon-sequencer": False,
"erigon-rpc": False,
"cdk-node": False,
},
```
> Option to add mitm as part of kurtosis deployment

- deploy_l2_contracts.star
- main.star
- src/package_io/ports.star
- templates/contract-deploy/run-l2-contract-setup.sh
Not funding the claimtxmanager account causes some problems. We run the `deploy_l2_contracts` by default, but only fund the claimtxmanager and skip everything else if it's `false`.
> feat: fund claim tx manager even if deploy l2 contracts is false

- .github/tests/chains/op-succinct.yml
- docker/op-succinct.Dockerfile
This PR updates the `op_succinct_contract_deployer_image` to the agglayer/op-succinct repo.
```
v0.0.4-agglayer : [https://github.com/agglayer/op-succinct/tree/6f34173a2a5a37fcc382ab5236b1033c48764848⁠](https://github.com/agglayer/op-succinct/tree/6f34173a2a5a37fcc382ab5236b1033c48764848)
v0.0.4 : [https://github.com/succinctlabs/op-succinct/tree/cb18ac0e512f153e40f4f2a59a55ceaecf3c298c⁠](https://github.com/succinctlabs/op-succinct/tree/cb18ac0e512f153e40f4f2a59a55ceaecf3c298c)
```
> chore: update op-succinct repo to agglayer version

- .github/tests/chains/op-succinct.yml
- input_parser.star
- lib/op_succinct.star
- revert agglayer image version to previous `main` tag
- change op network blocktime to 1s
- Integrate two new env variables for op-succinct:
```
op_succinct_max_concurrent_proof_requests: "1"
op_succinct_max_concurrent_witness_gen: "1"
```
Setting these to `1` will only send a single proof to the SPN and sequentially send pending proofs only after the previous requests are fulfilled.
Reference in [official docs](https://github.com/succinctlabs/op-succinct/blob/main/book/advanced/proposer.md#advanced-environment-variables)
> feat: change max concurrent proof/witness requests to 1

- input_parser.star
- templates/trusted-node/cdk-node-config.toml
- Fix `GlobalExitRootAddr` to point to L2 value
- Only run op `args_sanity_check()` if op deployment enabled. This should fix [aggkit ci](https://github.com/agglayer/aggkit/actions/runs/13810762478/job/38634400645?pr=292#step:10:1345)
> fix: L2 config for GlobalExitRootAddr

- .github/tests/chains/op-succinct.yml
- lib/op_succinct.star
- lib/service.star
- templates/op-succinct/deploy-op-succinct-contracts.sh
- This bumps the op-succint version to match https://github.com/agglayer/op-succinct/commit/f3f35308d5ae320cb7526c17d7378707a6c2e082
- The new images fix the error logs in the op-succinct-proposer
> chore: version bump on op-succinct with important bug fix

- docs/multi-pp-testing/README
- docs/multi-pp-testing/README.md
This PR fixes several typos in the `docs/multi-pp-testing/README` and `docs/multi-pp-testing/README.md` files.  
The key changes include:  
- Correcting "dont" → "don't" in the Bash script.  
- Fixing "worth while" → "worthwhile" in the vkey confirmation section.  
- Updating "address" → "addresses" in the funding instructions.  
- Correcting "purpsoes" → "purposes" in the token minting section.
> Fix typos in README for Multi-PP Testing

- deploy_sovereign_contracts.star
- deploy_zkevm_contracts.star
- input_parser.star
- main.star
- templates/aggkit/aggkit-config.toml
- templates/sovereign-rollup/run-sovereign-setup-predeployed.sh
Changes required for the stack to use predeployed contracts.
```
#!/bin/bash
ENCLAVE_NAME="op"
KURTOSIS_ARGS='{ 
"deployment_stages": {
"deploy_optimism_rollup": true,
},
"optimism_package": {
"source": "github.com/xavier-romero/optimism-package/main.star",
"predeployed_contracts": true
}
}'
kurtosis run --enclave $ENCLAVE_NAME . "$KURTOSIS_ARGS"
```
- https://github.com/ethpandaops/optimism-package/compare/main...xavier-romero:optimism-package:main
- https://github.com/ethereum-optimism/optimism/compare/v1.11.0...xavier-romero:optimism:feature/predeployed_contracts?expand=1
> Option to use OP predeployed contracts

- docs/blockscout.md
- docs/environment-migration.org
- docs/fast-iteration-cycle.md
- ✅ `docs/environment-migration.org`
- Fixed typos: `udpate → update`, `Unfortately → Unfortunately`
- Reworded: simplified the sentence about deploying a new sequencer for clarity and conciseness.
- ✅ `docs/fast-iteration-cycle.md`
- Minor edits to improve readability and technical tone consistency (e.g., "params" → "parameters").
- ✅ `docs/blockscout.md`
- Fixed repeated typo: `blockscot_backend_port → blockscout_backend_port` in multiple places.
- Improved phrasing for clarity in public IP/port explanation.
> Fix typos and improve clarity in documentation

- src/additional_services/bridge_spammer.star
The bridge spammer was sending transactions on l2 to the wrong address. It looks like the service file was only passing one of the addresses.
> fix: issue where we were missing bridge l2 address

- input_parser.star
- src/package_io/constants.star
When running the `pre-deployed-gas-token` test, it fails because of the following error:
```bash
Evaluation error: fail: Gas token address set to '0xb4B46bdAA835F8E4b4d8e208B6559cD267851051' but gas token is not enabled
```
This is because the check implemented in the sanity check module is wrong.
- Failing job: https://github.com/0xPolygon/kurtosis-cdk/actions/runs/14587822421/job/40916421933
- Successful job: https://github.com/leovct/kurtosis-cdk/actions/runs/14590317089/job/40923866110
> fix: gas token check

- .github/tests/chains/op2.yml
- cdk_central_environment.star
- input_parser.star
- lib/cdk_node.star
- templates/contract-deploy/create-keystores.sh
- templates/sovereign-rollup/create-predeployed-sovereign-genesis.sh
- templates/sovereign-rollup/run-initialize-rollup.sh
- Fix the `op2.yml` args file to allow attaching second op-geth network to the existing enclave with something like `kurtosis run --enclave=aggkit --args-file=./.github/tests/chains/op2.yml .` 
- Remove `zkevm_l2_claimsponsor_address` which was originally intended to be used as a separate address for the aggkit bridge. But having both `zkevm_l2_claimtxmanager_address` and `zkevm_l2_claimsponsor_address` could be confusing.
- Fix an issue on the `create-predeployed-sovereign-genesis.sh` script where the output that would be copied to create the allocs would be the incorrect default (example) output
> fix: op2.yml args file + cleanup

- .github/tests/chains/op-succinct-real-prover.yml
- .github/tests/chains/op-succinct.yml
- .github/tests/chains/op2.yml
- .github/tests/combinations/fork12-cdk-erigon-sovereign.yml
- .github/tests/consensus/sovereign.yml
- .github/tests/nightly/op-rollup/op-default.yml
- input_parser.star
This PR updates the images of agglayer and aggkit prover with corresponding `vkeys` and `selectors` for the `PP` - `FEP` upgrade.
The `vkey` from the prover now comes with prefixed `0x`, so this PR removes the format code in the `vkey` check.
> feat: update images and vkeys

- input_parser.star
- lib/cdk_node.star
- templates/aggkit/aggkit-cdk-config.toml
- templates/aggkit/aggkit-config.toml
- templates/trusted-node/cdk-node-config.toml
Remove trailing slash from aggkit/cdk data path in order to make it valid, since for the most components in the aggkit and cdk, default is specified this way `PathRWData/<data_storage>.sql`, which results in double slashes (e.g. `tmp//aggsender.sql`)
> fix: remove trailing slash from aggkit/cdk data path

- templates/aggkit/aggkit-config.toml
We have introduced retry policies for GRPC calls in the aggkit. It changed the aggkit configuration layout a bit.
The configuration evolved from this:
```toml
AggLayerURL = "{{AggLayerURL}}"
```
to this:
```toml
[AggSender.AgglayerClient]
URL = "{{AggLayerURL}}"
MinConnectTimeout = "5s"
RequestTimeout = "5s"
UseTLS = false
[AggSender.AgglayerClient.Retry]
InitialBackoff = "1s"
MaxBackoff = "10s"
BackoffMultiplier = 2.0
MaxAttempts = 8
[AggSender.AgglayerClient.Retry.Excluded]
Service = "agglayer.node.v1.ConfigurationService"
Method = "GetEpochConfiguration"
```
Affected configuration sections:
- `AggSender.AggLayerURL` -> `AggSender.AgglayerClient`
- `AggSender.AggchainProofURL` -> `AggSender.AggkitProverClient`
- `AggchainProofGen.AggchainProofURL` -> …
> feat: add Aggkit Prover gRPC server URL configuration

- lib/service.star
- src/additional_services/status_checker.star
- static_files/additional_services/status-checker-config/checks/lib.sh
- static_files/additional_services/status-checker-config/checks/rpc-sequencer-sync.sh
- static_files/additional_services/status-checker-config/checks/trusted.sh
- static_files/additional_services/status-checker-config/checks/verified.sh
- static_files/additional_services/status-checker-config/checks/virtual.sh
- Uses the sequencer URL to ensure that batches are still being produced
- Adds an additional check to notify when the sequencer and rpc are out of sync
> fix: use sequencer url in stuck batches status checks

- .github/workflows/docs-build.yml
- .github/workflows/docs-deploy.yml
- .github/workflows/kurtosis-deploy.yml
- .github/workflows/kurtosis-lint.yml
- .github/workflows/security-build.yml
Streamline the CI pipeline, particularly the `docs-deploy` workflow, as it seems some jobs are not triggered when pull requests are merged into the main branch. This results in GH uploading the artifact but only rendering the README, causing the documentation website to display differently than intended.
> ci: remove ignore paths

- templates/aggkit/aggkit-config.toml
The `[AggchainProofGen.AggchainProofURL]` config field is deprecated in favor of `[AggchainProofURL.AggkitProverClient.URL]`. This PR fixes the aggkit configuration.
For more info about aggkit config changes, refer to https://github.com/agglayer/aggkit/pull/570 and https://github.com/0xPolygon/kurtosis-cdk/pull/653.
> fix: remove deprecated `AggchainProofURL` field from aggkit config

- .github/tests/combinations/fork12-cdk-erigon-sovereign.yml
- .github/tests/consensus/sovereign.yml
- aggkit.star
- lib/aggkit.star
- templates/aggkit/aggkit-config.toml
- Disable `aggoracle` component for `pessimistic` consensus type
- format aggkit config and remove `L2Coinbase` parameter as it is unused
- cleanup `get_aggkit_cmd` in `aggkit.star`, as the branching was not necessary
> disable aggoracle component for fork12-cdk-erigon-sovereign

- .github/workflows/test.yml
- docs/docs/version-matrix.md
- When a PR is raised from a fork, the `Generate version matrix` step will fail because the fork will not have access to the `GITHUB_TOKEN` env variable which is required to run this step:
```
"Error: GITHUB_TOKEN environment variable is not set.
Please set it to access GitHub API for version information."
```
- This PR adds a check to see if the PR was raised from a fork, and if true, skip this check.
- The downside of this approach is that it will require more strict reviews from the maintainers, especially to check if there is a change in the version matrix when a PR is coming from a fork.
> tests: handle missing github token from forks

- deploy_sovereign_contracts.star
- templates/contract-deploy/run-deploy-l1-agglayer-core-contracts.sh
- templates/sovereign-rollup/fund-addresses.sh
When initializing the fund account, the system typically determines whether to use the test account or the specified mnemonic phrase based on the value of the `rpc_url` parameter:
```bash
if [[ "$RPC_URL" == "http://op-el-1-op-geth-op-node-001:8545" ]]; then
```
Note the op 's service will use `deployment_suffix` for it 's service name:
```yaml
"network_params": {
"name": DEFAULT_ARGS.get("deployment_suffix")[1:],
"network_id": str(DEFAULT_ROLLUP_ARGS.get("zkevm_rollup_chain_id")),
"seconds_per_slot": 1,
"isthmus_time_offset": 0,
},
``` 
And for all deploy code, the `deployment_suffix` should be eq to the op 's network_params 's `deployment_suffix`, if not eq, it will make a lots of errors.
However, when a custom `deployment_suffix` value is used for op 's network_params, the actual …
> fix fund failed by `deployment_suffix`

- .github/tests/chains/op-succinct-real-prover.yml
- .github/tests/chains/op2.yml
In versions prior to sp1 SDK v5.0.4, the sp1_prover_key could not include a '0x' prefix. This change removes the '0x' prefix from the example to ensure compatibility and successful execution of the full prover mode.
https://github.com/succinctlabs/sp1/commit/fdf70a42d56d2da7b37ccb832c742f21b054195c
> feat: delete 0x prefix for sp1_prover_key

- docs/docs/version-matrix.md
- input_parser.star
- cdk-erigon: `v2.61.24`
- op-batcher: `v1.15.0`
> chore: bump cdk-erigon and op-batcher

- .github/workflows/test.yml
- Remove 6 enclave deployments from the ci
- Rename two jobs
> ci: move fork 9, 11 and 13 tests to nightly

- templates/contract-deploy/run-create-agglayer-rollup.sh
- Add a bridge transaction within the setup script to make sure L2s with custom gas tokens have sufficient gas tokens on the L2 bridge to avoid balancetree underflow reverts.
- Adding this logic into the Kurtosis setup script will allow us to maintain consistent tests without needing to implement this redundant logic into the existing tests
> feat: bridge gas token to L2 during setup

- .github/tests/cdk-erigon/aggchain-ecdsa-multisig.yml
- .github/tests/op-geth/aggchain-ecdsa-multisig.yml
- .github/tests/op-succinct/mock-prover.yml
- .github/tests/op-succinct/real-prover.yml
- docs/docs/version-matrix.md
- src/package_io/constants.star
Aggkit prover release [v1.4.2
](https://github.com/agglayer/provers/releases/tag/v1.4.2)
> chore: update aggkit-prover
